name: CI

on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  build:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2023-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run tests on robot code
      run: ./gradlew build
      
  spotless:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Run Spotless check on robot code 
        run: ./gradlew spotlessCheck
